# Default Economic Model Parameters
# Configuration file for the Economics Cobb-Douglas model

# Solow Growth Model Parameters
solow_model:
  savings_rate: 0.20              # s - Fraction of output saved/invested
  population_growth_rate: 0.005   # n - Annual population growth rate
  technology_growth_rate: 0.02    # g - Annual technological progress rate
  depreciation_rate: 0.05         # delta - Annual capital depreciation rate
  capital_elasticity: 0.35        # alpha - Capital's share in production
  initial_technology: 1.0         # A0 - Initial technology level
  initial_labor: 100              # L0 - Initial labor force
  initial_capital: 10000          # K0 - Initial capital stock

# Financial Analysis Parameters
financial_model:
  beta: 1.0                       # Market beta (systematic risk)
  equity_risk_premium: 0.05       # Market risk premium
  expected_inflation: 0.02        # Expected annual inflation rate
  term_premium: 0.01              # Term structure premium
  retention_rate: 0.35            # Earnings retention rate (1 - payout ratio)
  total_factor_productivity: 1.1  # Earnings growth adjustment factor

# Monte Carlo Simulation Parameters
monte_carlo:
  num_simulations: 1000           # Number of simulation runs
  time_horizon_months: 12         # Time horizon in months
  
  # Technology growth rate distribution
  tech_growth:
    mean: 0.02                    # Mean annual technology growth
    std_dev: 0.005                # Standard deviation
  
  # Inflation rate distribution
  inflation:
    mean: 0.02                    # Mean annual inflation
    std_dev: 0.01                 # Standard deviation
  
  # Term premium distribution
  term_premium:
    mean: 0.005                   # Mean term premium
    std_dev: 0.002                # Standard deviation

# Visualization Settings
visualization:
  default_figure_size: [12, 6]    # Default plot size [width, height]
  color_scheme:
    growth_rate: "green"
    capital: "blue"
    output: "red"
    technology: "orange"
    labor: "purple"
    pe_ratio: "blue"
    earnings: "green"
  
  # Plot styling
  grid_alpha: 0.3
  line_width: 2
  marker_size: 4

# Analysis Settings
analysis:
  default_simulation_periods: 1000
  convergence_tolerance: 1e-6
  max_iterations: 10000
  
  # Sensitivity analysis ranges
  sensitivity_analysis:
    tech_growth_min: 0.01
    tech_growth_max: 0.03
    tech_growth_step: 0.001
    
    savings_rate_min: 0.10
    savings_rate_max: 0.30
    savings_rate_step: 0.01

# Scenario Definitions
scenarios:
  conservative:
    savings_rate: 0.15
    population_growth_rate: 0.003
    technology_growth_rate: 0.015
    depreciation_rate: 0.06
    capital_elasticity: 0.30
  
  base_case:
    savings_rate: 0.20
    population_growth_rate: 0.005
    technology_growth_rate: 0.020
    depreciation_rate: 0.05
    capital_elasticity: 0.35
  
  optimistic:
    savings_rate: 0.25
    population_growth_rate: 0.007
    technology_growth_rate: 0.025
    depreciation_rate: 0.04
    capital_elasticity: 0.40

# Data Export Settings
export:
  output_directory: "data/results"
  file_formats: ["csv", "json", "xlsx"]
  include_metadata: true
  timestamp_files: true
